# Generated by Django 4.1.3 on 2022-11-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0002_alter_subscribe_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscribe',
            name='parameter',
            field=models.IntegerField(choices=[(1, 'One'), (3, 'Three'), (6, 'Six'), (12, 'Twelve')], default=3),
        ),
    ]
